name: ci-docker

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Build 
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
