name: WINDOWS BUILD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: thealphavideo
        
    - uses: papeloto/action-zip@v1
      with:
        files: thealphavideo/dist/windows/
        dest: alpha-video.zip
          
    - uses: actions/upload-artifact@v2
      with:
        name: alpha-video
        path: alpha-video.zip
  
