name: WINDOWS BUILD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: alpha_video

    - uses: actions/upload-artifact@v2
      with:
        name: alpha-video
        path: alpha_video/dist/windows
